apiVersion: v1
kind: Service
metadata:
  name: {{ include "sgr-chart.fullname" . }}
  labels:
    {{- include "sgr-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8010
      protocol: TCP
      name: http
  selector:
    {{- include "sgr-chart.selectorLabels" . | nindent 4 }}
